TCL_VERSION = 8.6.15
TCL_VERSION_WORDS = $(subst ., ,$(TCL_VERSION))
TCL_SHORT_VERSION := $(word 1,$(TCL_VERSION_WORDS)).$(word 2,$(TCL_VERSION_WORDS))
TCL_WASM_LIB = $(WASM)/lib/libtcl$(TCL_SHORT_VERSION).a
TCL_WASM_CONFIG = $(WASM)/lib/tclConfig.sh
TCL_WASM_LIBRARY_DIR = $(WASM)/lib/tcl$(TCL_SHORT_VERSION)
OPTIONAL_WASM_LIBS += $(TCL_WASM_LIB)
WASM_LAZY_VFS += -i "$(TCL_WASM_LIBRARY_DIR)@/usr/lib/tcl$(TCL_SHORT_VERSION)"
